apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
      organizationID: ${SECRET_BWS_ORGANIZATION_ID}
      projectID: ${SECRET_BWS_PROJECT_ID}
