apiVersion: v1
data:
  bookmarks.yaml: |
    - Communicate:
        - Discord:
            - icon: discord.png
              href: 'https://discord.com/app'
        - Gmail:
            - icon: gmail.png
              href: 'http://gmail.com'
        - Google Calendar:
            - icon: google-calendar.png
              href: 'https://calendar.google.com'
        - Outlook:
            - icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/outlook.png
              href: 'https://outlook.com'
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
        - Spotify:
            - icon: spotify.png
              href: 'http://open.spotify.com'
        - Youtube Music:
            - icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/youtube-music.png
              href: 'https://music.youtube.com'
    - Reading:
        - Beyond:
            - icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/beyond.png
              href: 'https://forums.beyond.ca/search.php?do=getnew&contenttype=vBForum_Post'
        - Western Subaru Club:
            - icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/wsc.png
              href: 'http://westernsubaruclub.com/smf/index.php?action=unread'
        - Reddit:
            - icon: reddit.png
              href: 'https://reddit.com'
    - Git:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: 'https://kubesearch.dev/'
        - home-ops:
            - icon: github.png
              href: 'https://github.com/joryirving/home-ops'
        - dashboard-icons:
            - icon: github.png
              href: 'https://github.com/walkxcode/dashboard-icons/blob/main/ICONS.md'
  docker.yaml: ''
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Network:
        - Cloudflared:
            href: https://dash.cloudflare.com/
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel Status
            widget:
              type: cloudflared
              accountid: ac3f4399cd7d405084def1e2bbbd187f
              tunnelid: 0015ed2b-b160-4e42-85ee-1e1a0fa90dc3
              key: 6edP2asJNkgI-Agr7ytAOFHdcLidsBlIwPT2WNzh
              fields: ["status"]
        - AdGuard Home:
            href: https://adguard.${SECRET_DOMAIN}
            icon: adguard-home.png
            description: Adguard Home Status
            widget:
              type: adguard
              url: https://192.168.5.2
              username: admin
              password: backup
        - Unifi:
            href: https://unifi.ui.com
            icon: unifi.png
            description: Unifi Dashboard
            widget:
              type: unifi
              url: https://unifi.default.svc.cluster.local
              username: unpoller
              password: Congenial-Docile-Residency9
    - Calendar:
        - Agenda:
            widget:
              type: calendar
              view: agenda # optional - possible values monthly, agenda
              maxEvents: 20 # optional - defaults to 10
              integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Sonarr # service name for that widget
                - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Radarr # service name for that widget
                - type: readarr # active widget type that is currently enabled on homepage - possible values: radarr, sonar>
                  service_group: Downloads # group name where widget exists
                  service_name: Readarr # service name for that widget
    - Infrastructure:
        - Portainer:
            href: &url http://192.168.5.5:9002
            icon: portainer.png
            description: Docker Container Management
            widget:
              type: portainer
              url: http://192.168.5.5:9002
              env: 2
              key: ptr_v9mrSg4g/6Qz/epPVugK8akVgkE46CDTX2IsUjAHIlo=
        - TrueNAS:
            href: https://nas.${SECRET_DOMAIN}
            icon: truenas-core.png
            description: NAS
            widget:
              type: truenas
              url: http://192.168.5.20
              username: truenas_admin
              password: backup
              # key: yourtruenasapikey # not required if using username / password
              enablePools: true # optional, defaults to false
              nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
    - Home:
        - Home-Assistant:
            href: https://hass.${SECRET_DOMAIN}
            icon: home-assistant.png
            description: Home Automation Software
            widget:
              type: homeassistant
              url: http://home-assistant.default.svc.cluster.local:8123
              key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI5OTVmYWQ2MDIyNjc0MTU1ODlmYWZlYzAyMWY4ODEzNCIsImlhdCI6MTczNDYwMzgxMCwiZXhwIjoyMDQ5OTYzODEwfQ.hoMH1D1mZp1CO6VZY4cqZfoOPE0hVPKhMyOZCYRtNrg
  settings.yaml: |
    title: Dashboard
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    useEqualHeights: true
    theme: dark
    # background:
    #   image: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/101518784_p0.jpg
    #   opacity: 20
    color: slate
    headerStyle: clean
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Network:
        # style: row
        # columns: 3
        icon: mdi-network
      # Games:
      #   style: row
      #   columns: 3
      #   icon: mdi-minecraft
      Calendar:
        style: column
        icon: mdi-calendar
      Video:
        style: column
        icon: mdi-play-circle
      Books:
        # style: row
        # columns: 2
        icon: mdi-book
      Infrastructure:
        # style: row
        # columns: 5
        icon: mdi-server
      Observability:
        # style: row
        # columns: 5
        icon: mdi-chart-line
      Home:
        # style: row
        # columns: 5
        icon: mdi-home-analytics
      Downloads:
        # style: row
        # columns: 3
        icon: mdi-download-circle
  widgets.yaml: |
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
    - openmeteo:
        label: Home
        latitude: {{LATITUDE}}
        longitude: {{LONGITUDE}}
        timezone: ${TIMEZONE}
        units: imperial
        cache: 5
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: homepage
  name: homepage-config
