apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4CSfs4/c6bnDDBfWiiwHgs86oSaGGa1tHB0+PjS4CayHu8+UT89bIw==,iv:wsXcuuBts8xO2Bd0dbJPQ52uuPua9aPjrLVwlj7shwQ=,tag:mFRzhd5/u2pC0Wc6yjxQfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ01XRERSNG9lMngySy9Q
            N05zMjEvUkl4NDg3eE9NMitodCtuMzNKS0ZNCm95Uld6enFqbFJEUXhIR28yTUFt
            YWdOVUk4QXArRVgzZFE0ZlVpVWZDSlkKLS0tIGplckgzNkE3eUlPZEpCdkRGdXV4
            Z2pIdFFzMGpoYmlaRVp1SEZ3emJJZE0KDldOF/xxEkhf5i262AXhRebdBjCRMhlS
            0MoHkUdoIy2QCNIcm/u5NqDt5MrO0U07WLTpBkhvJ8F1abSoHmXOMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T01:49:08Z"
    mac: ENC[AES256_GCM,data:vxD8x9C669lg87bbL5l70XvzfuWBWbXJII+9qdYGVh83ZnuoPdPV2BvfxZsSKq7krpLiP1FxPdsdnfYisOHIiKSeQJZoAxO7yXKK1rn4eCAP9FQcH5j/PNR9uaVqRuGgXDM9XgNoqXI8XaBARbU+R1w8I0uKGBugMGNZcAzlFZQ=,iv:8QkSAhW/iG7mnlMtZAXCdMzvsx9LnzAeMlPGu2XjovI=,tag:qsHc/0LG4Y6ZhB8767XTLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
